### PR TITLE
fixing in calculations and layout

### PR DESCRIPTION
**Pull request by pavelbidenko2018**
1. add rating and comments  auto update
2. fix some layout on the landing and navbar

### CODE REVIEW

**Review by okozmovskaya — APPROVED** [review]

**Comment by okozmovskaya** [comment]
I approved. Just for suggestion: may be change place between buttons "Submit" and "Close" inside field for comment?)))

**Comment by pavelbidenko2018** [comment]
> I approved. Just for suggestion: may be change place between buttons "Submit" and "Close" inside field for comment?)))

Thank you, @okozmovskaya 
Done!

**Comment by IrynaSpyrydonova** [comment]
@pavelbidenko2018 everything looks and works great, just one thing, when i am not sign in and trying to give a score - i got an error or i suppose to add checking if the user is Auth? 
Screenshot 2021-01-17 at 21 54 47

**Comment by pavelbidenko2018** [comment]
> @pavelbidenko2018 everything looks and works great, just one thing, when i am not sign in and trying to give a score - i got an error or i suppose to add checking if the user is Auth?
> Screenshot 2021-01-17 at 21 54 47

Hi @IrynaSpyrydonova 
Yes, this error occurs when triyng to cast unauthorized user to ObjectId for Users Collection
In your #125 you already have the unauthorized user checking before querying DB 💯

**Pull request merged**
