### PR TITLE
Validation email

### PR DESCRIPTION
**Pull request by IrynaSpyrydonova**
Guys, in order to check how it works locally please change in routes => User.js => userRouter.post('/register') CLIENT_URL into "http://localhost:3000" (or at what port your frontend in running.
I have check this PR in my heroku account, you can see it [here](https://testforischool.herokuapp.com/)

### CODE REVIEW

**Comment by IrynaSpyrydonova** [comment]
Guys, in order to check how it works locally please change in routes => User.js => userRouter.post('/register') CLIENT_URL into "http://localhost:3000" (or at what port your frontend in running.
I have check this PR in my heroku account, you can see it [here](https://testforischool.herokuapp.com/)

**Review by pavelbidenko2018 — APPROVED** [review]

**Comment by pavelbidenko2018** [comment]
Hi @IrynaSpyrydonova 
could not understand why the .env file is exposed on the gitHub? 
We already put it to gitignore, did not we?

**Comment by IrynaSpyrydonova** [comment]
@pavelbidenko2018  yes, we did, but since first time i sent it to everyone to be able to login, logout (there is secret JWT) so now unfortunately github keep adding it 🤷🏻‍♀️. I was thinking that after we finish we will remove it manually

**Review by fmkarakus — APPROVED** [review]

**Comment by fmkarakus** [comment]
Hi @IrynaSpyrydonova , can you merge this yourself? Since package.json files are involved, i don't want to break anything :)

**Pull request merged**
