### PR TITLE
connected mongoDB, wrote readme with instructions, user, school schemas

### LINKED ISSUE #21: MongoDB connection
-  [ ] - user and School schemas 
-  [ ] - connection to mongoDB
-  [ ] - readme with instructions

### PR DESCRIPTION
**Pull request by IrynaSpyrydonova**
Closes gh-21

### CODE REVIEW

**Review by fmkarakus — CHANGES_REQUESTED** [review]
All looks fine!
I have some suggestions in SchoolSchema
For the `areas`, type could be an array since a school may have many areas.
For the `networks` we can use more common names like
```
network:{
        type: String,
         enum : ['GO Network','Catholic Network','Municipality Schools','Private schools' ],
        required:[true, 'Network is required']
    },
```

**Comment by IrynaSpyrydonova** [comment]
@fmkarakus  thank you, I made changes

**Review by fmkarakus — APPROVED** [review]

**Review by pavelbidenko2018 — COMMENTED** [review]
Hi @IrynaSpyrydonova!
Maybe we should not create a separate schema like GeoSchema? The reason is that Geoschema could not exist without conjunction with the owner (School or User)

We couldjust include property `location` to both School and User models

```js
 location: {
        type: {
            type: String,
            enum: ['Point'],
            required: true
        },
        coordinates: {
            type: [Number],
            required: true
        }
    },`

**Comment by pavelbidenko2018** [comment]
@IrynaSpyrydonova 
How do you think, maybe we also include School adress?
```js
adress:{
city:{type:String},
street:{type:String},
num:{type:String}
}

**Comment by IrynaSpyrydonova** [comment]
@pavelbidenko2018  but what is the problem with using Geo schema? At least I know that creating our geometry with lat and long this way  works perfect with query of Mongo DB $near. Have you check if it works with location? if yes, then I am fine with both 🙂

**Comment by pavelbidenko2018** [comment]
@IrynaSpyrydonova 
For me looks super, an most of all this Schema works with geo functions 👍 💯 
Could you just edit adress field: /post code was added and not null requirenments/ 
```js
 adress: {
        postcode: {
            type: Number,
            required: [true, 'Post code is required']
        },

        city: { type: String, default: 'Gent' },
        street: {
            type: String,
            required: [true, 'Street is required']
        },
        building: {
            type: String,
            required: [true, 'Building No is required']
        },

    },

**Comment by IrynaSpyrydonova** [comment]
yes, it works, I check now several times with get, post requests and near method, all of them are working fine

**Comment by IrynaSpyrydonova** [comment]
@pavelbidenko2018 l changed again address as you asked

**Pull request merged**
