### PR TITLE
Multiple choice filter with checkbox instead radio

### LINKED ISSUE #69: Search page:  Filter page radio button but is better with the checkbox not everywhere School Network / School Field
- [ ] Change School Network / School Field radio buttons with checkboxes.

### LINKED ISSUE #110: Convert radio to checkboxes

### PR DESCRIPTION
**Pull request by okozmovskaya**
Guys, I added checkboxes instead radio and fixed the bug with stars in filter container, check please.
Close #69 and close #110

### CODE REVIEW

**Review by fmkarakus — COMMENTED** [review]
Hi @okozmovskaya, i tested the branch. You have done a lot of work.
I see that the behavior of filter is  changed now. I need to select school network and field parameters in order to the the search. It is Ok, if this was the intention.
Also reset button does not uncheck the check-boxes. When I click reset button then search button, I get no results. 
Good luck...

**Comment by IrynaSpyrydonova** [comment]
@okozmovskaya Thank you very much for your work 🙏🏻  But some things are still a bit confusing, for instance can I filter only for reception classes? it gives me always 0 result, same for only schools with rating 5 or 4 stars and so on ..

**Comment by okozmovskaya** [comment]
@IrynaSpyrydonova , @fmkarakus  Thank you for your check and comments, I fixed:
1. Language filter
2. Reset button
3. Style for rating stars (we haven't school with rating 1 and 2 that's why I think some rating show incorrect result)

And Fatih, I don't understand about it: "I need to select school network and field parameters in order to the the search. It is Ok, if this was the intention" - what you means?

**Comment by okozmovskaya** [comment]
@julia-sod  I ask you to check the size of images for info-page. I tried to make it responsive for all screens, but I'm not sure that it works correctly.
Also I changed icon for My school (on heart, not star, because we can have conflict with style of stars from rating). And added the variant of favicon.

Sorry that in this branch, not in separate 🤪

Close #104, close #105

**Comment by IrynaSpyrydonova** [comment]
@okozmovskaya  looks very good for me only one thing can be improved : we have rating with decimals (like 2.3 , 4.4) can we rounded the result of searching? otherwise if i choose only 4 star it gives me only 4, but results with decimals we will never find.  But its not critical. Thank you very much.

**Comment by fmkarakus** [comment]
Hi @okozmovskaya. It works better now. 
- I also agree with Ira. When we select 3 stars, for example,it may show the schools whose rating is rounded to 3 (in other words from 2.5 to 3.4))
- When I click reset button, it doesn't erase/uncheck ratings
- What I said was same as what Ira said in her first comment so don't worry about it anymore.

**Comment by julia-sod** [comment]
Hi @okozmovskaya! That's really loads of work you're doing! About images, it doesn't look working properly for me neither. But here what can be tried. I just changed images to backgrounds. So you use only divs with class names, without pasting the src. So it becomes more responsive(at least worked for me🙈). 
And I put such changes into css for image1, for example:
    background-image: url("./assets/education.jpg");
    background-repeat: no-repeat;
    background-size: contain;
    margin-top: 8%
It seems working. Hope it makes sense🤗
All the rest looks good for me! Thank you a lot

**Comment by okozmovskaya** [comment]
Guys, sorry for so many bugs, now it works:
1. Return all decimal for rating
2. Reset rating filter

**Review by julia-sod — APPROVED** [review]
Well done!

**Review by IrynaSpyrydonova — APPROVED** [review]
@okozmovskaya  thank you very much )) everything works great 👍

**Review by fmkarakus — APPROVED** [review]
Well done!

**Pull request merged**
