### PR TITLE
Favorites backend

### LINKED ISSUE #52: Add favorite schools
User will be able add favorite schools in the database
- [ ] add routes
- [ ] add controllers

### PR DESCRIPTION
**Pull request by fmkarakus**
closes #52

### CODE REVIEW

**Review by pavelbidenko2018 — APPROVED** [review]
For me OK 👍
Are we going to set a possibillity to manage a school item from favorities list?
When a user gets a list from DB and wants to delete smth from it?

**Review by IrynaSpyrydonova — COMMENTED** [review]
@fmkarakus  very good job, thank you. But there is one issue. Whenever i put new school in my listOfSchools - it overwrites the previous one and in the array always one value, but suppose to add every time a new one. Or I am wrong?

**Comment by fmkarakus** [comment]
@pavelbidenko2018 , @IrynaSpyrydonova 
This is how I thought: In front end we add or delete a school from array of favorite schools, then we send the updated array to back end. And it overwrites. How do you think? Should I add or delete one by one?

**Comment by IrynaSpyrydonova** [comment]
My point is that when we added new school it should add one to the listOfSchools, but not overwrite all of them, otherwise user will  always have one school in the list

**Comment by pavelbidenko2018** [comment]
To my opinion it sounds quite logical: 
* if the list of favourite schools is already exists in database, we fetch it to the client's array object, work with it. for example delete an item and than sends the list back to the DB
* if not - all work will be provided on the client and the result Array object would be sent on the server

**Pull request merged**
